export const ActionType = {
  PAGE: "PAGE",
  TRENDING_MOVIES: "TRENDING_MOVIES",
  TRENDING_TV: "TRENDING_TV",
  MOVIEFAVOURITES: "MOVIEFAVOURITES",
  TVFAVOURITES: "TVFAVOURITES",
  ISSIGNUP: "ISSIGNUP",
  ISSIGNIN: "ISSIGNIN",
  USERNAME: "USERNAME",
};
